# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/dma_demo/dma_demo.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_demo || ORIG_REF_NAME==dma_demo} -quiet] -quiet

# IP: bd/dma_demo/ip/dma_demo_processing_system7_0_0/dma_demo_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_demo_processing_system7_0_0 || ORIG_REF_NAME==dma_demo_processing_system7_0_0} -quiet] -quiet

# IP: bd/dma_demo/ip/dma_demo_ps7_0_axi_periph_0/dma_demo_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_demo_ps7_0_axi_periph_0 || ORIG_REF_NAME==dma_demo_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/dma_demo/ip/dma_demo_rst_ps7_0_50M_0/dma_demo_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_demo_rst_ps7_0_50M_0 || ORIG_REF_NAME==dma_demo_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/dma_demo/ip/dma_demo_axi_mem_intercon_0/dma_demo_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_demo_axi_mem_intercon_0 || ORIG_REF_NAME==dma_demo_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/dma_demo/ip/dma_demo_axi_cdma_0_0/dma_demo_axi_cdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_demo_axi_cdma_0_0 || ORIG_REF_NAME==dma_demo_axi_cdma_0_0} -quiet] -quiet

# IP: bd/dma_demo/ip/dma_demo_auto_pc_0/dma_demo_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_demo_auto_pc_0 || ORIG_REF_NAME==dma_demo_auto_pc_0} -quiet] -quiet

# IP: bd/dma_demo/ip/dma_demo_auto_pc_1/dma_demo_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_demo_auto_pc_1 || ORIG_REF_NAME==dma_demo_auto_pc_1} -quiet] -quiet

# IP: bd/dma_demo/ip/dma_demo_auto_us_0/dma_demo_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dma_demo_auto_us_0 || ORIG_REF_NAME==dma_demo_auto_us_0} -quiet] -quiet

# XDC: /home/rom41797/Documents/Project/CDMA_simple_polling_DDR/project_1.gen/sources_1/bd/dma_demo/dma_demo_ooc.xdc
